### ISSUE TITLE
Special characters problem

### ISSUE THREAD

**Issue by mykeehu** [Vasyanator/google_translate_plus#2]
I love your accessories and they are almost perfect! 

I noticed that sometimes the apostrophe (') and quotation mark (") are not returned correctly by Google translate. I get the web versions back, so the `&#x27;` and `&quot;` appear in the text. 

Is there any way to fix this?

**Comment by Vasyanator** [comment]
I hope you didn't download this, because there was an overly suspicious link in that deleted comment. I've encountered that but didn't pay attention, I'll try to fix it now.

**Comment by Vasyanator** [comment]
Fixed

**Comment by mykeehu** [comment]
Wow! That was very fast, thank you very much! I didn't download the spam. Thank you very much!
