### ISSUE TITLE
Something happened in the last update with the text between signs

### ISSUE THREAD

**Issue by mykeehu** [Vasyanator/google_translate_plus#3]
In my chat, I use <> or ¤ characters to indicate narrative text. For example: <He left the building> or  ¤He left the building¤ Brackets was converted to `&lt;` and `&gt;` before the last update, so HTML code, which is not good. 
I upgraded to the latest build, but now it does not translate the text between the characters, even though no such character is listed as an exception in the settings. 
What could be the problem?

Update 1: The cb8d8218b6aedc970b669e448722b408ef91382c git works fine, I'm back to that now.

**Comment by Vasyanator** [comment]
I tried fixing the bug, but I can't test that right now. Please let me know the result.

**Comment by mykeehu** [comment]
Unfortunately, the part of the bug that doesn't translate the text between the signs is still there. I get this error in the debug prompt:
`[Google translate plus]: Error: Special symbol cannot be empty.`

You can simply reproduce the text below to start the chat:
`¤Hello, how are you today? Hope you're ready for another chat!¤`

Update: Okay, I just typed the ~ sign in the special symbol field, it seems to be fixed. Thanks for the quick fix!

**Comment by Vasyanator** [comment]
Under this parameter, there was an explanation that some characters can cause errors. Apparently it needs to be improved.

**Comment by mykeehu** [comment]
For me it was empty, because I wanted to use the ~ character. So it doesn't work empty, unfortunately.
